---
# Common setup applied before all playbooks
#
# - Password and authentication handling
# - Optional overrides for compatibility issues
#

- name: Apply common configurations
  hosts: all
  # Enable/disable fact gathering as needed. Should be disabled if causing problems with Python interpreter (mainly on older versions)
  gather_facts: no 
  # gather_facts: false 
  become: no
  become_method: sudo
  # In case of password fail because of host parallelism
  # serial: 3

  vars_files:
  - /etc/ansible/secrets.yml

  vars:
    ansible_connection_timeout: 5
    ansible_command_timeout: 5
    ansible_ssh_retries: 1
    ansible_timeout: 5
    ansible_ssh_retry_delay: 0.1
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o UserKnownHostsFile=/dev/null' #any_errors_fatal: false
    log_file: "/var/log/os_version_check.log"
    
  tasks:
  - name: Ensure ansible_ssh_pass is set
    set_fact:
      ansible_ssh_pass: "{{ passwords[inventory_hostname] }}"
      ansible_become_pass: "{{ passwords[inventory_hostname] }}"
    no_log: true

  - name: Coletar fatos do sistema
    setup:

  roles:
    - common

