---
- name: Verificar versão do sistema operacional nos hosts
  hosts: all
  become: yes
  gather_facts: no

  vars_files:
    - /etc/ansible/secrets.yml

  vars:
    ansible_connection_timeout: 5
    ansible_command_timeout: 5
    ansible_ssh_retries: 1
    ansible_timeout: 5
    ansible_ssh_retry_delay: 0.1
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o UserKnownHostsFile=/dev/null'
    log_file: "/var/log/os_version_check.log"

  tasks:

    - name: Definir senha SSH a partir do arquivo de segredos
      set_fact:
        ansible_ssh_pass: "{{ passwords[inventory_hostname] }}"
        ansible_become_pass: "{{ passwords[inventory_hostname] }}"
      no_log: true
      tags: always
    
    - name: coletar fatos do sistema
      setup:    


    - name: Exibir distribuição e versão do sistema operacional
      debug:
        msg: "Sistema operacional: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      tags: so

    - name: Obter data e hora do servidor
      command: date
      register: resultado_data
      changed_when: false
      tags: data

    - name: Exibir data e hora
      debug:
        msg: "Data e hora do servidor: {{ resultado_data.stdout }}"
      tags: data

    - name: Exibir endereço IP e hostname
      debug:
        msg: "Host: {{ ansible_hostname }} - IP: {{ ansible_default_ipv4.address }}"
      tags: rede

    - name: Mostrar tempo de atividade
      command: uptime
      register: resultado_uptime
      changed_when: false
      tags: sistema

    - name: Exibir uptime
      debug:
        msg: "Tempo de atividade: {{ resultado_uptime.stdout }}"
      tags: sistema

    - name: Verificar uso de disco
      command: df -h /
      register: resultado_disco
      changed_when: false
      tags: disco

    - name: Exibir uso de disco
      debug:
        msg: "{{ resultado_disco.stdout_lines }}"
      tags: disco

    - name: Verificar uso de memória
      command: free -h
      register: resultado_memoria
      changed_when: false
      tags: memoria

    - name: Exibir uso de memória
      debug:
        msg: "{{ resultado_memoria.stdout_lines }}"
      tags: memoria

    - name: Mostrar versão do kernel
      debug:
        msg: "Kernel: {{ ansible_kernel }}"
      tags: sistema

   
...
