---
- name: Check OS Version on All Hosts
  hosts: all
  become: no
  gather_facts: no #Explicitly disable fact gathering to avoid the initial connection attempts
  vars_files:
    - /etc/ansible/secrets.yml
  vars:
    ansible_connection_timeout: 5
    ansible_command_timeout: 5
    ansible_ssh_retries: 1
    ansible_timeout: 5
    ansible_ssh_retry_delay: 0.1
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o UserKnownHostsFile=/dev/null'
      #any_errors_fatal: false
    log_file: "/var/log/os_version_check.log"

  tasks:
    - name: Ensure ansible_ssh_pass is set
      set_fact:
        ansible_ssh_pass: "{{ passwords[inventory_hostname] }}"
      no_log: true

    - name: Coletar fatos do sistema
      setup:

    - name: Mostrar S.O.
      debug:
        msg: "SO: {{ ansible_distribution }} {{ ansible_distribution_version }}"
    
    - name: Mostar data e hora do servidor
      command: date
      register: resultado_data

    - name: Exibir a data e a hora
      debug:
        msg: "a data e a hora são: {{resultado_data.stdout }}"
    
      
          
