---
- name: Verificar versão do sistema operacional nos hosts
  hosts: glpi 
  become: yes
  gather_facts: no

  vars_files:
    - /etc/ansible/secrets.yml

  vars:
    ansible_connection_timeout: 5
    ansible_command_timeout: 5
    ansible_ssh_retries: 1
    ansible_timeout: 5
    ansible_ssh_retry_delay: 0.1
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o UserKnownHostsFile=/dev/null'
    log_file: "/var/log/os_version_check.log"

  tasks:

    - name: Definir senha SSH a partir do arquivo de segredos
      set_fact:
        ansible_ssh_pass: "{{ passwords[inventory_hostname] }}"
        ansible_become_pass: "{{ passwords[inventory_hostname] }}"
      no_log: true
      tags: always
    
    - name: coletar fatos do sistema
      setup: 

    - name: Exibir distribuição e versão do sistema operacional
      debug:
        msg: "Sistema operacional: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      tags: so

    - name: Atualizar o cache do apt
      apt:
        update_cache: yes

    - name: Instalar pacotes necessários
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Baixar e executar o script oficial do Docker
      shell: curl -fsSL https://get.docker.com | sh

    - name: Baixar a versão mais recente do Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.37.3/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verificar a versão do Docker Compose
      shell: docker-compose --version
      register: docker_compose_version

    - name: Exibir a versão do Docker Compose
      debug:
        msg: "{{ docker_compose_version.stdout }}"
