---
- name:  My first play
  hosts: all
  become: no
  gather_facts: no
  vars_files:
    - /etc/ansible/secrets.yml
  vars:
    ansible_connection_timeout: 5
    ansible_command_timeout: 5
    ansible_ssh_retries: 1
    ansible_timeout: 5
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o UserKnownHostsFile=/dev/null'  

  tasks:
    - name: Ensure ansible_ssh_pass is set
      set_fact:
        ansible_ssh_pass: "{{ passwords[inventory_hostname] }}"
      no_log: true

 
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
...          
