---
- name: Check OS version and update on all hosts
  hosts: all
  become: yes
  gather_facts: no

  vars_files:
    - /etc/ansible/secrets.yml

  vars:
    ansible_connection_timeout: 5
    ansible_command_timeout: 5
    ansible_ssh_retries: 1
    ansible_timeout: 5
    ansible_ssh_retry_delay: 0.1
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o UserKnownHostsFile=/dev/null'
    log_file: "/var/log/os_version_check.log"

  tasks:
    - name: Ensure ansible_ssh_pass is set
      set_fact:
        ansible_ssh_pass: "{{ passwords[inventory_hostname] }}"
        ansible_become_pass: "{{ passwords[inventory_hostname] }}"
      no_log: true
    
    - name: coletar fatos do sistema
      setup:

    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: Instalar o calendario do terminal
      apt:
        name: ncal
        state: present  
...
